name: Workflow "dummy" para BE-Payments

on:
  push:
    branches:
      - main

jobs:
    ir_a_buscar_yml_a_principal:
        name: Ir a buscar el yml de repo Principal
        uses: ObligatorioArbeloRodriguez/Principal/.github/workflows/main.yml@main
        with:
            app_name: be-payments
            sonar_project_key: ObligatorioArbeloRodriguez_BE-Payments
            nombre_repo_ecr: payments-repo
        secrets:
            inherit